- hosts: all
  tasks:
    - name: ansible create directory example
      file:
        path: /home/azureuser/fyc/hedi
        state: directory
 
    - name: download package
      get_url:
        url: http://20.188.42.94:8081/repository/maven-releases/org/fyc/weather-jar/1.2.0/weather-jar-1.2.0.jar
        dest: /home/azureuser/fyc/hedi
        mode: 0755
        force_basic_auth: yes
