- hosts: all
  tasks:
    - name: ansible create directory example
      file:
        path: /home/azureuser/fyc/"{{ ansible_date_time.date}}"
        state: directory
 
    - name: download package
      get_url:
        url: http://20.188.42.94:8081/repository/maven-releases/org/fyc/weather-jar/1.2.0/weather-jar-1.2.0.jar
        dest: /repository/maven-releases/livraison-1.2.0
        mode: 0755
        force_basic_auth: yes
  
   - name: fetsh package
     fetch:
        src: /home/azureuser/fyc/livraison-1.2.0
        dest: /home/azureuser/fyc/"{{ ansible_date_time.date}}"
        mode: 0755
        owner: azureuser
        group: root
      
